# Generated by Django 4.1.5 on 2023-01-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='TrueOrFalse',
        ),
    ]
